image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      lando start
      lando composer install
      lando drush cim -y
      lando drush updb -y
      lando drush cr
      cd web/themes/custom/contribtracker
      npm i
      npx gulp
      cd -

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - whatwedo.twig
    - marcostazi.vs-code-drupal
